version: '3.8'

services:
  wa-sender:
    build: .
    container_name: wa-sender
    restart: unless-stopped
    environment:
      - HEADLESS=true
      - SESSION_PATH=/app/session
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage
    volumes:
      - ./session:/app/session
      - ./src/data:/app/dist/src/data
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
